genome_url: "https://ftp.ensembl.org/pub/release-112/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna_sm.toplevel.fa.gz"
genome_name: "sc_R64"
data_root: "data"
orf_max_len: 300